name: Deploy to Maven Central
on:
  workflow_dispatch:
    inputs:
      version-increment:
        description: 'Version-increment'
        required: true
        type: choice
        options:
          - patch
          - minor

jobs:
  deploy-maven:
    uses: entur/gha-maven-central/.github/workflows/maven-publish.yml@main
    secrets: inherit
    with:
      next_version: ${{ inputs.version-increment }}
      version_strategy: tag
      version_tag_prefix: legacy-v

  post-failure-to-slack:
    needs: deploy-maven
    if: failure()
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ vars.CHANNEL_ID }}
      message: "ðŸ”´ Maven artifact deploy failed for ${{ github.repository }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit

  post-success-to-slack:
    needs: deploy-maven
    if: success()
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ vars.CHANNEL_ID}}
      message: "ðŸŸ¢ Maven artifact deploy success for ${{ github.repository }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit


